[project]
name="yoda"
version="0.0.1"
description="Centralised System Automations with LLM"
readme="README.md"
requires-python=">=3.10.11"
dependencies=[
    "art",
    "cryptography"
]

[project.scripts]
yo="cli.main:main"
